config/routes.rb
Testing::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show]

  scope ':locale' do
    resources :buckets, :only => [ :index ]
    resources :items, :only => [ :index, :show, :edit, :update ]
  end
 resources :prisms

  get 'home', to: "pages#index", as: :home
  get 'about', to: "pages#about", as: :about
  get 'alumni', to: "pages#alumni", as: :alumni
  get 'terms', to: "pages#terms", as: :terms
  get 'future', to: "pages#future", as: :future
  get 'demo', to: "pages#demo", as: :demo

  
  match '/prisms/:id/visualize(.:format)', to: 'prisms#visualize', as: 'visualize', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight', as: 'highlight', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight_post', as: 'highlight_post', via: [:post]
  match '/myprisms/', to: 'users#show', as: :users, via: [:get]
  match '/prisms/:id/destroy(.:format)', to: 'prisms#destroy', as: :destroy, via: [:all]
  match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook', via: [:get]

  root :to => 'pages#index'

end

app/models/prism.rb
class Prism < ActiveRecord::Base
  has_many :word_markings, -> {:facet}, :dependent => :delete_all
  belongs_to :users
  has_many :facets, :dependent => :delete_all
  validates_presence_of :title, :content, :license

# A prism is the document a user wishes other readers to interpret along particular facets.
# In other words, a prism is an uploaded text which a group of readers is expected to mark along pre-selected interpretive categories.
# A document, when uploaded, is split into an array consisting of individual words.

  self.primary_key ='uuid'

  before_create :set_uuid
  def set_uuid
    require 'uuidtools'
    self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end

  def add_content_spans
    return if content.nil? or content.empty?
    return if title.nil?   or title.empty?
    return if license.nil? or license.empty?

    doc = Nokogiri::XML("")
    doc << doc.create_element("content")
    counter = 0

    content.each_line do |line|
      line.gsub!(/\A +/) { |m| "&nbsp;" * m.size }
      line.gsub!(/\t/)   { |m| "&nbsp;&nbsp;&nbsp;" }

      paragraph = doc.create_element("p")
      doc.root.add_child(paragraph)

      span_list = line.split(" ").map do |word|
        span = doc.create_element("span", :class => "word word_#{counter}")
        span << word + ' '
        counter += 1
        span
      end
      span_nodeset = Nokogiri::XML::NodeSet.new(doc, span_list)
      paragraph << span_nodeset
    end

    self.content   = doc.root.to_s
    self.num_words = counter
  end

  def calc_frequencies
      frequencies = {}

    self.facets.each do |facet|
      frequencies[facet.order] = [0.0] * self.num_words
    end

    self.word_markings.each do |word_marking|
      frequencies[word_marking.facet.order][word_marking.index] += 1.0
    end

    frequencies
  end


end

app/controllers/prisms_controller.rb
require 'set'

class PrismsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :highlight, :highlight_post]
  before_filter :get_prism, :only => [:highlight, :highlight_post, :destroy]

  #caches_action :index, :layout => false
  caches_action :show, :layout => false
  caches_action :visualize, :layout => false

  def index
    @prisms = Prism.paginate(:page => params[:page], :per_page => 10)

    for prism in Prism.all
      if !prism.unlisted
        @prisms << prism
      end
    end

    respond_to do |format|
      format.html
      format.json { render :json => @prisms }
    end
  end

  def highlight
  end

  def highlight_post

    @prism.facets.each do |facet|
      param   = params[("facet#{facet.order}_indices").to_sym]
      indexes = WordMarking.parseJSONArray param
      WordMarking.importIndexes current_user, @prism, facet, indexes
    end
    expire_action :action => :visualize
    redirect_to(visualize_path(@prism))
  end

  def visualize
    @title = "Visualize"

    @prism = Prism.includes(:word_markings).find(params[:id])

    # doesn't seem to ever get used?
    # @word_markings = @prism.word_markings
    @usercounter = 0
    @user_num = @prism.word_markings.map(&:user_id).uniq
    @frequencies = @prism.calc_frequencies

  end

  def new
    @prism = Prism.new
    @facet1 = Facet.new
    @facet2 = Facet.new
    @facet3 = Facet.new
    @language_dump = LanguageList::COMMON_LANGUAGES
    @languages = []
    @language_dump.each do |lang|
      @languages.push(lang.name)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prism }
    end
  end

  def create

    @prism = Prism.new(params[:prism])
    @prism.user_id = current_user.id
    @facet1 = Facet.new(params[:facet1])
    @facet2 = Facet.new(params[:facet2])
    @facet3 = Facet.new(params[:facet3])

    @facet1.order = 0
    @facet1.color = "blue"
    @facet2.order = 1
    @facet2.color = "red"
    @facet3.order = 2
    @facet3.color = "green"

    @prism.add_content_spans
    success = @prism.save

    if @facet1.description.to_s.length > 0
      @facet1.prism = @prism
      success = success && @facet1.save
    end
    if @facet2.description.to_s.length > 0
      @facet2.prism = @prism
      success = success && @facet2.save
    end
    if @facet3.description.to_s.length > 0
      @facet3.prism = @prism
      success = success && @facet3.save
    end

    respond_to do |format|
      if success
        if @prism.unlisted?
          notice = "Success! Keep in mind that this prism will not show up in the public browse page. Be sure to copy the link to send to your friends!"
        else
          notice = "Prism was successfully created."
        end
        format.html { redirect_to highlight_path(@prism), notice: notice }
        format.json { render json: @prism, status: :created, location: @prism }
      else
        format.html { render action: "new" }
        format.json { render json: @prism.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    respond_to do |format|
      if authorize! :destroy, @prism
        @prism.destroy
        format.html { redirect_to users_path, notice: 'Prism was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to users_path, notice: 'Prism could not be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def get_prism
    @prism = Prism.find(params[:id])
  end

end

app/views/prisms/_cc_license.html.erb
<%# TODO: this needs to be refactored in to a model %>

<% case license
  when 'cc0' %>
This work is public domain.
<% when 'by' %>
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>.
<% when 'by-nd' %>
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nd/3.0/deed.en_US">Creative Commons Attribution-NoDerivs 3.0 Unported License</a>.
<% when 'by-nc-sa' %>
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.
<% when 'by-sa' %>
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_US">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
<% when 'by-nc' %>
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/deed.en_US">Creative Commons Attribution-NonCommercial 3.0 Unported License</a>.
<% when 'by-nc-nd' %>
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US">Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License</a>.
<% when 'fair-use' %>
  The contributer of this Prism asserts fair use of this material.
<% end %>

app/views/prisms/_cc_license_form.html.erb
<div class="field">
<label for="prism[license]">License</label>
<select name="prism[license]">
     <option value="by" selected="selected">CC Attribution</option> 
     <option value="by-nd">CC Attribution-NoDerivs</option>
     <option value="by-nc-sa">CC Attribution-NonCommercial-ShareAlike</option>
     <option value="by-sa">CC Attribution-ShareAlike </option>
     <option value="by-nc">CC Attribution-NonCommercial</option>
     <option value="by-nc-nd">CC Attribution-NonCommercial-NoDerivs</option>
     <option value="cc0">Public Domain</option>
     <option value="fair-use">Fair Use</option>
     <option value="none">None</option>
</select>
<%= link_to('About the licenses', 'https://creativecommons.org/licenses/') %>
</div>

app/views/prisms/_vizopts.html.erb
<div id="visualizations">

  <span class="vis_selection">
    <h3>Winning Facet Visualization</h3>
    <input type="hidden" class="vis_type" value="winning_facet" />
  </span>
  <div>
	  <p class="chart_title">Click a word to display highlight data.</p>
    <div id="chart_div"></div>
    <li class="vis_button" style="display:none;">
      <input type="hidden" class="color" value="winning"/>
      <input type="hidden" class="order" value=""/>
      <input type="hidden" value="<%= frequencies[0] %>" class="freq"/>
      <span class="facet red green blue"></span>Winning Facet
    </li>
    <span class="current-word" style="display:none;"></span>
    <ul id="mousevoer-stats" style="display:none;">
      <li><span class="red-percent red-vis"></span></li>
      <li><span class="green-percent green-vis"></span></li>
      <li><span class="blue-percent blue-vis"></span></li>
    </ul>

    <p id="visualization-help"><%= t "visualize.winningdescription" %> </p>
    <p id="visualization-mouse"><%= t "visualize.mouse" %> </p>
  </div>

    <span class="vis_selection">
    <h3>Font Size Visualization</h3>
    <input type="hidden" class="vis_type" value="font_size" />
  </span>
  <div>
    <p id="visualization-help"><%= t "visualize.instructions" %></p>
    <ul id="highlighters">
    <% facets.each do |facet| %>
      <li class="vis_facet vis_button">
        <input type="hidden" class="color" value="<%= facet.color %>"/>
        <input type="hidden" class="order" value="<%= facet.order %>"/>
        <input type="hidden" value="<%= frequencies[facet.order] %>" class="freq"/>
        <span class="facet <%= facet.order %> <%= facet.color %>"></span><%= facet.description %>
      </li>
    <% end %>
    </ul>
  </div>

</div>

app/views/prisms/highlight.html.erb
<% title "Highlight" %>
<% content_for :extra_head do %>
  <script type="text/javascript" charset="utf-8">
$(setup_highlight);
</script>
<% end %>

<div id="Prismabob">
  <h1><%= @prism.title.html_safe + " - " + @prism.publication_date %></h1>
  <h2><%= @prism.author %></h2>
  <div class="text noselect" unselectable="on">
    <%= @prism.content.html_safe %>
  </div>
</div>

<div id="highlight_sidebar" class="noselect" unselectable="on">
  <div id="tools">
    <ul id="highlighters">
      <% for facet in @prism.facets %>
        <li class ="facet">
      <input type="hidden" name = "order" value="<%=facet.order%>"/>
      <input type="hidden" name = "color" value="<%=facet.color%>"/>
      <span class="facet <%=facet.color%>"></span><%=facet.description%>
    </li>
    <% end %>
      <li class="facet eraser"><input type="hidden" name="order" value="delete"/><span class="facet"><%= image_tag ('eraser3.png'), :id => 'eraser' %></span><%= t "highlight.eraser" %></li>
    </ul>

    <%= form_tag do %>
      <% for facet in @prism.facets %>
      <input type="hidden" value="" name="facet<%=facet.order%>_indices" id="facet<%=facet.order%>_indices"/>
  <% end %>
    <input type="submit" value="Save Highlights" class='button'/>
  <% end %>

    <div id="highlight_instructions">
      <h1>INSTRUCTIONS</h1>
      <p><%= t "highlight.instructions" %></p>
    </div>

    <div id="description">
      <h1>DESCRIPTION</h1>
      <p><%= @prism.description %></p>
    </div>

    <div id="license">
      <h1>LICENSE</h1>
      <p><%= render 'cc_license', :license => @prism.license.downcase %></p>
    </div>

  </div>
</div>

app/views/prisms/index.html.erb
<% title "Browse" %>

<%= link_to 'New prism', new_prism_path, :id => 'new-prism', :class => 'button' %>

<h1>Browse Prisms</h1>

<table cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th>Title</th>
      <th>Highlight</th>
      <th>Visualize</th>
    </tr>

  </thead>

  <tbody>

  <% @prisms.each do |prism| %>
    <tr>

    <td><%= prism.title.html_safe %></td>

    <td class="highlight"> <%= link_to(highlight_path(prism), :class => 'highlight') do %>
      <%= image_tag('highlight_button.png') %>
    <% end %>
    </td>


    <td class="visualize">  <%= link_to(visualize_path(prism), :class => 'visualize') do %>
      <%= image_tag('visualize_button.png') %>
    <% end %>
    </td>

  </tr>
<% end %>


  </tbody>


</table>

<div id="pagination">
	<%= will_paginate @prisms %>
</div>

app/views/prisms/new.html.erb
<% title "New Prism" %>
<h1>New Prism</h1>

<%= form_for(@prism) do |f| %>
  <% if @prism.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@prism.errors.count, "error") %> prohibited this prism from being saved:</h2>

    <ul>
      <% @prism.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field" id="content">
    <%= f.label :content %>
    <%= f.text_area :content, :placeholder => 'Required: The Text Your Group Will Be Highlighting' %>
  </div>

  <div id="sidebar">
    <div id="facetbutton">
     <%= fields_for :facet1 do |f1| %>
        <div class="field">
          <%= image_tag('facetblue.png') %>
          <%= f1.text_field :description, :placeholder => 'Facet 1' %>
        </div>
      <% end %>

      <%= fields_for :facet2 do |f2| %>
        <div class="field">
        <%= image_tag('facetred.png') %>
          <%= f2.text_field :description, :placeholder => 'Facet 2' %>
        </div>
      <% end %>

      <%= fields_for :facet3 do |f3| %>
        <div class="field">
          <%= image_tag('facetgreen.png') %>
          <%= f3.text_field :description, :placeholder => 'Facet 3' %>
        </div>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, :placeholder => 'Required: Give Your Prism a Title!'  %>
    </div>
    <div class="field">
      <%= f.label :author %>
      <%= f.text_field :author, :placeholder => 'Required: Original Author'  %>
    </div>
    <div class="field">
      <%= f.label :publication_date %>
      <%= f.text_field :publication_date, :placeholder => 'You Know the Drill...mm/dd/year'  %>
    </div>
    <div class="field">
      <% @language_dump = LanguageList::COMMON_LANGUAGES %>
      <% @languages = [] %>
      <% @language_dump.each do |lang| %>
        <% @languages.push(lang.name) %>
      <% end %>
      <%= f.label :language %>
      <%= f.select :language, options_for_select(@languages, "English") %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, :rows => 6, :placeholder => 'What do you want people to know about this text or your facet categories?' %>
    </div>
    <div class ="field">
      <%= f.check_box :unlisted%>
      <%= f.label :unlisted %>
      <p>Check this box if you want to share your prism with friends only (you'll need to email the link to friends).</p>
    </div>

    <%= render "cc_license_form" %>

    <div class="actions">
      <p>Wait! Before you submit, read our <%= link_to "Terms of Service", terms_path %>!</p>
      <%= f.submit :class => 'button' %>
    </div>
  </div>
<% end %>

app/views/prisms/visualize.html.erb
<% title "Visualise" %>
<div style="display:none;">view updated</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
$(function() {
    setup_visualize();
    select_vis($("span.vis_selection")[0]);

    $( "#visualizations" ).accordion({heightStyle: "content"});
});

google.charts.load('current', {packages: ['corechart']});
google.charts.setOnLoadCallback(drawChart);
</script>

<div id="Prismabob">
  <h1><%= @prism.title.html_safe %></h1>
  <h2><%= @prism.author %></h2>

  <div class="text">
    <%= @prism.content.html_safe %>
  </div>
</div>
<div id="sidebar">
  <%= render 'vizopts', :facets => @prism.facets, :frequencies => @frequencies %>
  <p><%= render 'cc_license', :license => @prism.license.downcase %></p>
  <p id="viz-count">
    <span>
    <% if @user_num != nil %>
    <%=@user_num.size %></span> 
    <% if @user_num.size == 1%>
      user 
    <% else%>
      users 
      <%end%>
      contributed to this visualization.
    <% end %>
  </p>
  <p id="highlight-link">
    <%= link_to "Highlight Text", highlight_path(@prism), class: "button", id: "highlight-button" %>
  </p>
</div>


