config/routes.rb
Testing::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show]

  scope ':locale' do
    resources :buckets, :only => [ :index ]
    resources :items, :only => [ :index, :show, :edit, :update ]
  end
 resources :prisms

  get 'home', to: "pages#index", as: :home
  get 'about', to: "pages#about", as: :about
  get 'alumni', to: "pages#alumni", as: :alumni
  get 'terms', to: "pages#terms", as: :terms
  get 'future', to: "pages#future", as: :future
  get 'demo', to: "pages#demo", as: :demo

  
  match '/prisms/:id/visualize(.:format)', to: 'prisms#visualize', as: 'visualize', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight', as: 'highlight', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight_post', as: 'highlight_post', via: [:post]
  match '/myprisms/', to: 'users#show', as: :users, via: [:get]
  match '/prisms/:id/destroy(.:format)', to: 'prisms#destroy', as: :destroy, via: [:all]
  match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook', via: [:get]

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w[admin user]

  has_many :prisms
  has_many :word_markings

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    User.find_from_auth(
      auth.provider, auth.info.email, auth.extra.raw_info.name, auth.uid
    )
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    User.find_from_auth('google', data['email'], data['name'], data['uid'])
  end

  def self.find_for_browserid_oauth(access_token, signed_in_resource=nil)
    data = access_token.info
    User.find_from_auth('browserid', data['email'], data['name'], data['uid'])
  end

  def self.find_from_auth(provider, email, name, uid)
    user = User.where(:email => email).first
    if user
      # Update the login information to the most current every time someone
      # logs in. This makes sure that the avatar is coming from wherever they
      # logged in from for that session.
      user.update_attributes(
        :provider => provider,
        :uid      => uid,
      )
    else
      user = User.create(
        name: name,
        provider: provider,
        uid: uid,
        email: email,
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user	
    if @user != nil
    	@prisms = @user.prisms
    	@highlighted_prisms = @user.word_markings.map(&:prism_id).uniq
    else
    	redirect_to :home
    	flash[:error] ="Sign in first!"
    end
  end
end

app/views/users/show.html.erb
<% title "My Prisms" %>

<%= link_to 'New prism', new_prism_path, :class => 'button', :id => 'new-prism' %>
  <h1>myPrisms (<%= @user.email %>)</h1>
  <%= image_tag(avatar_url(current_user), :class => "avatar") %>

<% if @prisms.length > 0 %>

  <h2>Owned Prisms</h2>
  <table cellpadding="0" cellspacing="0">
    <thead>
      <tr>
        <th>Title</th>
        <th>Highlight</th>
        <th>Visualize</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @prisms.each do |prism| %>
        <tr>
          <td><%= prism.title.html_safe %></td>
          <td class="highlight">
            <%= link_to(highlight_path(prism), :class => 'highlight') do %>
              <%= image_tag('highlight_button.png') %>
            <% end %>
          </td>
          <td class="visualize">
            <%= link_to(visualize_path(prism), :class => 'visualize') do %>
              <%= image_tag('visualize_button.png') %>
            <% end %>
          </td>
          <td class="delete">
            <% if can? :destroy, prism %>
              <%= link_to(destroy_path(prism), :confirm => 'Are you sure you want to delete this prism? The prism, collaborative interpretation, and all of its related highlights will be permanently deleted.', :class => 'destroy') do %>
                <%= image_tag('delete_button.png') %>
                <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>Have unlisted Prisms? Just copy and email the link to share with your Friends!</p>

  <% else %>

  <p>You have not added any Prisms. <%= link_to 'Add a Prism', new_prism_path %>

  <% end %>

<% if @highlighted_prisms.size > 0 %>
  <h2>Highlighted Prisms</h2>
  <table cellpadding="0" cellspacing="0">
    <thead>
      <tr>
        <th>Title</th>
        <th>Highlight</th>
        <th>Visualize</th>
      </tr>
    </thead>
    <tbody>
      <% @highlighted_prisms.each do |stuff| %>
        <tr>
          <% prism = Prism.find_by_uuid(stuff) %>
          <td><%= prism.title.html_safe %></td>
          <td class="highlight">
            <%= link_to(highlight_path(prism), :class => 'highlight') do %>
              <%= image_tag('highlight_button.png') %>
            <% end %>
          </td>
          <td class="visualize">
            <%= link_to(visualize_path(prism), :class => 'visualize') do %>
              <%= image_tag('visualize_button.png') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p> You have not highlighted any Prisms. <%= link_to 'Highlight a Prism', prisms_path %>
<% end %>