config/routes.rb
Testing::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show]

  scope ':locale' do
    resources :buckets, :only => [ :index ]
    resources :items, :only => [ :index, :show, :edit, :update ]
  end
 resources :prisms

  get 'home', to: "pages#index", as: :home
  get 'about', to: "pages#about", as: :about
  get 'alumni', to: "pages#alumni", as: :alumni
  get 'terms', to: "pages#terms", as: :terms
  get 'future', to: "pages#future", as: :future
  get 'demo', to: "pages#demo", as: :demo

  
  match '/prisms/:id/visualize(.:format)', to: 'prisms#visualize', as: 'visualize', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight', as: 'highlight', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight_post', as: 'highlight_post', via: [:post]
  match '/myprisms/', to: 'users#show', as: :users, via: [:get]
  match '/prisms/:id/destroy(.:format)', to: 'prisms#destroy', as: :destroy, via: [:all]
  match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook', via: [:get]

  root :to => 'pages#index'

end

app/views/pages/about.html.erb
<% title "About" %>
<div class="callout teacher-notice">
  <h3 id="note-to-teachers" >A Note to Teachers</h3>

  <p class="notice">
  Prism was created by novice student developers in the <a href="http://praxis.scholarslab.org">Praxis Program</a>.
  It has been recently discovered by the K-12 community, and is seeing heavy use right now. Prism is an experimental tool.
  It <strong>may</strong> break. It may be down during your class time. We can make no guarantees about availability, but are glad you are helping to test the tool! </p>

  <p>If you have questions about how to use Prism or if you want to share ideas for doing so, please visit our <a href="https://groups.google.com/forum/#!forum/prism-community">community forum</a>. To suggest features or request support for bugs, create an issue on our <a href="https://github.com/scholarslab/prism/issues?state=open">Github page</a>.
  </p>

  <p>&ndash; The Praxis Team</p>
</div>

<h1><%= t 'about.prism_title' %></h1><hr>
<p><%= t 'about.description_p1_html' %></p>
<p><%=t 'about.description_p1half_html' %></p>
<blockquote><p><%= t 'about.description_p2' %></p></blockquote>
<p><%= t 'about.description_p3_html' %></p>
<p><%= t 'about.description_p4_html' %></p>
<p><%= t 'about.description_p5_html' %></p>
<p><%= t 'about.description_p6_html' %></p>
<h3>Future Directions</h3>
<hr/>
<p><%= t 'about.description_p7_html' %></p>
<h2><%= t 'about.contributors_title' %></h2>
<hr/>
<div id="contributors-fellows"><p><%= t 'about.contributors_fellows_html' %></p></div>

<div id="Praxis">
  <h2><%= t 'about.praxis_title' %></h2><hr>
  <p><%= t 'about.praxis_description_html' %></p>

  <h2><%= t 'about.scholarslab_title' %></h2><hr>
  <p><%= t 'about.scholarslab_description_html' %></p>
  <div id="contributors-advisors"><p><%= t 'about.contributors_advisors_html' %></p></div>

</div>

app/views/pages/alumni.html.erb
<% title "Alumni" %>

<div class="page-margin">
  <div id="page-content">
    <h1><%= t 'alumni.alumni_title' %></h1> 

    <h2><%= t 'alumni.year_title' %></h2>
    <div id="contributors-alumni"><p><%= t 'alumni.contributors_alumni_html' %></p></div>

  </div>
</div>

app/views/pages/demo.html.erb
<% title "Demo" %>
<div class="page-margin">
  <div id="page-content">
    <h1><center>Click the Play Button to View the Prism Tutorial!</center></h1> 
    <p><center><iframe width="560" height="315" src="http://www.youtube.com/embed/AxHDcW15UBI" frameborder="0" allowfullscreen></iframe></center></p>
    


</div>

</div>

app/views/pages/future.html.erb
<% title "Future Directions" %>
<div class="page-margin">
  <div id="page-content">
    <h1>Future Directions</h1> 

    <h2>Thinking About Texts</h2>
    <p>Although the 2012-2013 cohort eventually chose to focus our efforts on expanding the word-based capabilities of Prism, we had many discussions throughout year about expanding our conception of “texts” to include more than the written word.   Could Prism be used to generate collaborative readings of photographs, maps, musical scores, or audio clips?   In response to this question, we came up with a number of ideas. Here, we have chosen to share some of those possibilities.</p> 

    <h2>Interpreting Photographs</h2>
    <p>There already exist a number of promising image-based web applications.   Projects such as <a href= "http://www.snapshotserengeti.org/">Snapshot Serengeti</a> use crowd sourcing to complete scholarly and research based projects.  Others, such as <a href=" http://lab.softwarestudies.com/p/imageplot.html">ImagePlot</a>, identify macro patterns through a series of images.  In addition, there are a number of applications which allow you to annotate images as an individual and perhaps view other annotations of the same document (e.g. <a href="http://mith.umd.edu/tile/">Tile</a>, <a href="http://tapor.uvic.ca/~mholmes/image_markup/index.php">Uvic</a>, and <a href="http://a.nnotate.com/">A.nnotate</a>).  However, most of these applications don’t allow you to overlay multiple annotations in order to generate a collaborative interpretation. That’s where Prism could come in.</p>

    <p>As a test case, we tried using the transparency game on an image.  Drawing on her own research interests, Cecilia presented us with the following image.  In a manner similar to the transparency game, we were then asked to highlight areas of the image that we identified as “southern.”  The exercise resulted in some surprising results.  In addition to highlighting the "colored" sign that was emblematic of the Jim Crow South, most readers also highlighted the boy's body.  It is striking that they would see blackness, or this black boy, as representative of the South.  One could argue that this is because of the proliferation of photographic images during the Workers Progress Administration that highlighted black, southern poverty.</p>

    
    <figure>
      <%= image_tag "southernimage.jpg" %>
      <figcaption>Jim Crow Drinking Fountain, county courthouse lawn. Halifax, North Carolina, 1938.</figcaption>
    </figure>
  

    <p>How can this exercise be executed in a digital format?  There are two basic problems.  How will users be able to interact with the image and how will the resulting data then be aggregated and visualized?  We discussed several options for highlighting images, but there are two which seem to hold the most promise.  First, the image could be divided up into various sections which the users can “tag” with various categories, much like the tagging feature on facebook.  To visualize the collaborative interpretation, we could then display the “winning” category for each section, much like the current option to display the winning facet for each word in Prism.  Secondly, users could be given a paintbrush tool which would allow them to highlight whichever elements on the page they see fit.  In that case, we could visualize the resulting interpretation through a heat map layered over the photograph.  Those portions that receive the most markings would turn red and the least blue, for example. </p>

    <h2>Word-based Texts: Additional Possibilites</h2> 
    <p>In addition, there are a number of ways in which Prism might expand its ability to work with written texts.  The first is to offer additional ways to visualize the collaborative interpretations.  Below are a number of sketches from the 2011-2012 Praxis team.  You can see that we have realized some of these ideas in this edition of Prism.  Users can now view a pie chart which presents the percentage of users who highlighted for each facet under the “winning color” visualization option.  In addition, provocative visualizations could draw upon existing web applications that use text mining, such as the word clouds generated through applications like <a href="http://voyant-tools.org/">Voyant</a>.</p>
    <p>Other possibilities for Prism include expanding the way in which Prism creates collaborative interpretations by relying on computational linguistic analysis.  Specifically, this would allow for a more open-ended interpretation process.  Imagine if users were free to apply any description they see fit to a passage of text or a particular word (similar to the capabilities offered by <a href="http://nowcomment.com/">NowComment</a>).   Prism would then process these comments through topic modeling (e.g. <a href="http://www.matthewjockers.net/">Jockers’ work</a>) to visualize the most common words invoked by users.  In addition, this process could be paired with a thesaurus in order to computationally identify synonyms, allowing for a more synthesized collaborative interpretation based on open-ended commentary from users.</p>



    <ul id="viz-sketches">
      <ul>
        <%= link_to image_tag('viz001.jpg', :width => "40%"), image_path('viz001.jpg') %><%= link_to image_tag('viz002.jpg', :width => "40%"), image_path('viz002.jpg') %>
      </ul>
      <ul>
        <%= link_to image_tag('viz003.jpg', :width => "40%"), image_path('viz003.jpg') %><%= link_to image_tag('viz004.jpg', :width => "40%"), image_path('viz004.jpg') %>
      </ul>

      <ul>
        <%= link_to image_tag('viz005.jpg', :width => "40%"), image_path('viz005.jpg') %><%= link_to image_tag('viz006.jpg', :width => "40%"), image_path('viz006.jpg') %>
      </ul>

    </ul>



  </div>

</div>

app/views/pages/index.html.erb
<% title "Home" %>


<!-- <div class="alert alert-warning">
  We will be performing maintenance on this site Monday, November 16, 2015 starting at 9:00 am EST.
</div> -->


<div id="buttons">
  <span><%= link_to 'Demo', demo_path, :class => 'demo' %></span>
  <span><%= link_to 'Create', new_prism_path, :class => 'create' %></span>
  <span><%= link_to 'Play', prisms_path, :class => 'play' %></span>
</div>

app/views/pages/terms.html.erb
<% title "Terms of Service" %>
<div class="page-margin">
  <div id="page-content">
    <h1>Terms of Service</h1> 
    <h2>Purpose and Scope of this Site</h2>
    <p>This site has been created under the ownership and control of the University of Virginia Library to allow use of the Prism program created by the Scholars' Lab Praxis Program.  Its purpose is to provide an online collaborative interpretive tool.  Through Prism, users are able to share texts and allow others to interact with those texts to create a collaborative interpretation. No submitted texts will be reviewed before being published online, but the Scholars' Lab does reserve the right to request revisions or remove any given texts. In other words, the Scholars' Lab Prism website has been established to allow for collaborative interpretation, and does not constitute a forum for general expression.</p>
    <h2>Legal Responsibilities</h2>
    <p>By submitting text to the Prism application, you agree that it is your individual responsibility to adhere to all applicable legal requirements including copyright law, and that you have not posted content that is defamatory of or harmful to the legal rights of others. You represent and warrant that you either own or have received permission to post the all content submitted, or that your excerpts from the original works of others are consistent with fair use guidelines under US copyright law.</p>
    <h2>Publication Rules</h2>
    <p>The Prism application and the resulting collaborative interpretations, or “prisms,” are published under the Creative Commons Attribution Public Use License.  This license does not interfere with your personal ability to reuse or republish self-authored content you post here, either in a commercial or noncommercial context.</p.>
    <p>When uploading text to Prism, you will be prompted to select the appropriate Creative Commons License.  Please note that this license covers the base text of your own authorship; it does not cover the resulting collaborative interpretation, or “prism.”  Visit the <a href="http://creativecommons.org/licenses/"> Commons License </a>website to learn more about the difference between each license.</p>
    <h2>Preservation</h2>
    <p>The University of Virginia Library does not promise backup, restoration, continued maintenance, or dedicated archiving of content created in through the Prism website. Any questions about these policies should be directed to scholarslab@virginia.edu.</p>
    <h2>YOUR CREATION OF A PRISM ACCOUNT INDICATES YOUR AGREEMENT WITH THE ABOVE TERMS.</h2> 
  </div>

</div>