config/routes.rb
Testing::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:show]

  scope ':locale' do
    resources :buckets, :only => [ :index ]
    resources :items, :only => [ :index, :show, :edit, :update ]
  end
 resources :prisms

  get 'home', to: "pages#index", as: :home
  get 'about', to: "pages#about", as: :about
  get 'alumni', to: "pages#alumni", as: :alumni
  get 'terms', to: "pages#terms", as: :terms
  get 'future', to: "pages#future", as: :future
  get 'demo', to: "pages#demo", as: :demo

  
  match '/prisms/:id/visualize(.:format)', to: 'prisms#visualize', as: 'visualize', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight', as: 'highlight', via: [:get]
  match '/prisms/:id/highlight(.:format)', to: 'prisms#highlight_post', as: 'highlight_post', via: [:post]
  match '/myprisms/', to: 'users#show', as: :users, via: [:get]
  match '/prisms/:id/destroy(.:format)', to: 'prisms#destroy', as: :destroy, via: [:all]
  match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook', via: [:get]

  root :to => 'pages#index'

end

app/views/layouts/_flashmessages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}", :class => "flashmessage" if msg.is_a?(String) %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>

  <div id="footernav">

    <a href="https://github.com/scholarslab/prism">Source Code</a>

    <a href="http://creativecommons.org/licenses/by/3.0/">CC-BY 3.0</a>

    <a href="https://github.com/scholarslab/prism/issues?state=open">Bugs &amp; Support</a>

    <a href="https://groups.google.com/forum/#!forum/prism-community">Forum</a>

    <%= link_to image_tag('http://static.scholarslab.org/images/logos/slab/slab-logo-black-200px.png'), "https://scholarslab.org", :id => 'slab-link' %>

  </div>

</footer>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<div id="user_meta">
        <!-- The following code shows the user's email if they are signed in. !-->
          <%= current_user.email %> |
          <%= link_to t('header.sign_out'), destroy_user_session_path, :method => :delete, :id => 'sign-out' %>
        <!-- end. !-->
</div>

<% end %>

<nav>
  <ul>
    <li>
      <%= link_to t('header.link_about'), about_path, {:class => 'about_link'}  %>
    </li>
    <li>
      <%= link_to t('header.link_documents'), prisms_path, {:class => "browse_link"} %>
    </li>
    <li>
    <% if user_signed_in? %>
        <%= link_to 'myPrisms', users_path(current_user), {:class => "myprisms_link"} %>
    <% else %>
        <%= link_to t('header.sign_in'), new_user_session_path, {:class => "sign_in_link"} %>
    <% end %>
    </li>
  </ul>
</nav>

<header>
  <div class="header">

    <%= link_to image_tag('LOGO.png'), root_path %>
    <% if current_page?('/') %>
      <p class="motto">A Tool for Collaborative Interpretation of Texts</p>
      <p><%= link_to('A Note to Teachers', about_path(:anchor =>'note-to-teachers'), :class => 'note') %></p>
    <% end %>

  </div>

</header>



<!--[if lt IE 9]>
<p id="browser-upgrade">Prism is built to support at least Internet Explorer 9. <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <title>Prism <%= yield :title %></title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag 'favicon.png' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <link href='http://fonts.googleapis.com/css?family=Quicksand|Source+Sans+Pro:200,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => nil %>
  <%= csrf_meta_tags %>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.5.3/modernizr.min.js"></script>
  <%= javascript_include_tag "application" %>
  <%= yield :extra_head %>
  <script type="text/javascript">
    var _gaq=_gaq||[];_gaq.push(['_setAccount','UA-12081576-4']);_gaq.push(['_trackPageview']);(function(){var ga=document.createElement('script');ga.type='text/javascript';ga.async=true;ga.src=('https:'==document.location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);})();
  </script>
</head>
<body id="<%= page_id %>">
  <div id="container">

    <%= render 'layouts/header' %>
    <%= render 'layouts/flashmessages'%>
    <div id="main" role="main">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </div>
<!--[if lt IE 7 ]>
  <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
  <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
<![endif]-->
</body>
</html>